# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'geolocator' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for geolocator
    pod 'Firebase/Core', '~> 5.15.0'
    pod 'Firebase/Auth', '~> 5.15.0'
    pod 'Firebase/Firestore', '~> 5.15.0'

  target 'geolocatorTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'geolocator-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for geolocator-tvOS

  target 'geolocator-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
